TheEvent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('events/', views.events_index, name='index'),
  path('events/<int:event_id>/', views.events_detail, name='detail'),
  path('events/create/', views.EventCreate.as_view(), name='events_create'),
  path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
  path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='events_delete'),
  path('events/<int:event_id>/comments/', views.events_comments, name='events_comments'),
  path('events/<int:event_id>/comments/create', views.CommentCreate.as_view(), name='comments_create'),
  path('events/<int:pk>/comments/update/', views.CommentUpdate.as_view(), name='comments_update'),
  path('events/<int:pk>/comments/delete/', views.CommentDelete.as_view(), name='comments_delete'),
  path('cats/<int:event_id>/add_photo/', views.add_photo, name='add_photo'),
  path('events/<int:event_id>/assoc_user/<int:user_id>/', views.assoc_user, name='assoc_user'),
  path('accounts/signup/', views.signup, name='signup'),
  path('events/<int:event_id>/attendees/', views.AttendeesList.as_view(), name='events_attendees'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

class Event(models.Model):
  eventTitle = models.CharField(max_length=100)
  description = models.TextField(max_length=2000)
  date = models.DateField('Event Date')
  evtLocation = models.CharField(max_length=50)
  organizer = models.ForeignKey(User, on_delete=models.CASCADE)
  attendees = models.ManyToManyField(User, related_name="attendees")
  
  def __str__(self):
    return f'{self.eventTitle} ({self.id})'

  def get_absolute_url(self):
        return reverse('detail', kwargs={'event_id': self.id})

class Comment(models.Model):
  comment = models.TextField(max_length=1000)
  event = models.ForeignKey(Event, on_delete=models.CASCADE)
  created_on = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  class Meta:
    ordering = ['created_on']

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12)

class Photo(models.Model):
    url = models.CharField(max_length=200)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for event_id: {self.event_id} @{self.url}"

main_app/forms.py
from .models import Comment, Event
from django.forms import ModelForm
from django import forms



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Event, Comment, User, Photo
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import CommentForm


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def events_index(request):
  events = Event.objects.all()
  return render(request, 'events/index.html', {
    'events': events
  })

def events_detail(request, event_id):
  event = Event.objects.get(id=event_id)
  attendees = User.objects.exclude(id__in = event.attendees.all().values_list('id'))
  comments_form = CommentForm()
  return render(request, 'events/detail.html', {
    'event': event,
    'comments_form': comments_form,
    'attendees': attendees
  })

def events_comments(request, event_id):
  form = CommentForm(request.POST)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.user = request.user
    new_comment.event_id = event_id 
    new_comment.save()
  return redirect('detail', event_id = event_id) 
  

class EventCreate(CreateView):
  model = Event
  fields = ['eventTitle', 'description', 'date', 'evtLocation']
  def form_valid(self, form):
    print(self.request.user)
    form.instance.organizer = User.objects.get(username=self.request.user)
    return super().form_valid(form)

class EventUpdate(UpdateView):
  model = Event
  fields = ['eventTitle', 'description', 'date', 'evtLocation']

class EventDelete(DeleteView):
  model = Event
  success_url = '/events'

def add_photo(request, event_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, event_id=event_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('detail', event_id=event_id)

class CommentCreate(CreateView):
  model = Comment
  fields = ['__all__']

class CommentUpdate(UpdateView):
  model = Comment
  fields = ['comment']

class CommentDelete(DeleteView):
  model = Comment
  def get_success_url(self):
    print("success")
    return f"/events/{self.object.event.id}"

class AttendeesList(ListView):
    model = User
    fields = '__all__'

def assoc_user(request, event_id, user_id):
    Event.objects.get(id=event_id).attendees.add(user_id)
    return redirect('detail', event_id=event_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h4>Welcome to the Event</h4>
  <br>
  <img src="https://i.imgur.com/hl24Npy.jpg" class="aboutimage">
{% endblock %}
  

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>The Event</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;<em>The Event</em></a></li>
        </ul>
        <ul class="right">
          {% if user.is_authenticated %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'events_create' %}">Add an Event</a></li>
          <li><a href="{% url 'index' %}">View All Events</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 The Event &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/events/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Event Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ event.eventTitle }}</span>
        {% for photo in event.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
        <p><em>Description:</em> {{ event.description }}</p>
        <br>
        <p><em>Organizer:</em> {{ event.organizer }}</p>
        <br>
        <p><em>Event Date:</em> {{ event.date }}</p>
        <br>
        <p><em>Location:</em> {{ event.evtLocation|linebreaks }}</p>
      </div>
      {% if event.organizer == request.user %}
      <div class="card-action">
        <a href="{% url 'events_update' event.id %}">Edit</a>
        <a href="{% url 'events_delete' event.id %}">Delete</a>
      </div>
      {% endif %}
      <form action="{% url 'add_photo' event.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <div>
        <input type="file" name="photo-file">
        </div>
        <br>
        <br>
        <button type="submit" class="btn"><i class="material-icons center-align"></i>Upload Photo</button>
      </form>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-content">
    <h5>{{ event.eventTitle }}'s Attendees</h5>
    <hr>
    {% if event.attendees.count %}
      {% for attendee in event.attendees.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             {{ attendee.username }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
    <br>
      <h6>No Attendees ☹️</h6>
    {% endif %}
  </div>
  <br>
  <div class="col s12 m6 14">
    <div class="card-panel">
    <h5>Available Attendees</h5>
    <hr>
    {% if attendees.count %}
      {% for attendee in attendees.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             {{ attendee.username }}
            </span>
          </div>
          {% if attendee == request.user %}
          <div class="card-action">
            <form action="{% url 'assoc_user' event.id attendee.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
          {% endif %}
        </div>
      {% endfor %}
    {% else %}
      <h6>Everyone's coming! 🥳</h6>
      <br>
    {% endif %}
    </div>
  </div>
</div>

<div class="col">
  <form action="{% url 'events_comments' event.id %}" class="form"  method="POST" style="color: white;">
    {% csrf_token %}
    {{ comments_form.as_p }}
    <input type="submit" value="Submit!" class="btn">
  </form>
  <table class="commentstable">
    {% if event.comment_set.count %}
      {% for comment in event.comment_set.all %}
      <tr>
        <td>{{ comment.user }}</td>
        <td>{{ comment.comment }}</td>
        {% if comment.user == request.user %}
        <td><a href="{% url 'comments_delete' comment.id %}">Delete</a></td>
        {% endif %}
      </tr>
      {% endfor %}
    {% else %}
    <h6>No Comments Yet</h6>
    {% endif%}
  </table>
</div>

{% endblock %}

main_app/templates/events/index.html
{% extends 'base.html' %}
{% block content %}


{% for event in events %}
  <a href="{% url 'detail' event.id %}">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ event.eventTitle }}</span>
        <p>Description: {{ event.description|linebreaks }}</p>
        <p>Date: {{ event.date }}</p>
        <p>Location: {{ event.evtLocation|linebreaks }}</p>
        {% if event.photo_set.count %}
          <div class="card-image">
            <img id="calendar-img" class="responsive-img" src="{{ event.photo_set.first.url }}" alt="photo of {{ event.eventTitle }}">
          </div>
        {% endif%}
      </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}


<h2>Sign up to join on the fun</h2>
<br>
<img src="https://i.imgur.com/KbWCfIP.jpg" class="homeimage">


{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}
 
{% block content %}
  <h2>Delete Comment</h2>
 
  <h4>Are you sure you want to delete this comment?</h4>
 
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' comment.event.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h2>Delete Event</h2>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' event.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/event_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h2>Edit Event</h1>
{% else %}
  <h2>Add Event</h2>
{% endif %}


<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
    <script>
        const dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
          format: 'yyyy-mm-dd',
          defaultDate: new Date(),
          setDefaultDate: true,
          autoClose: true
        });
    </script>
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}